server:
  port: 8080
  # servlet上下文路径，默认/，
  servlet:
    context-path: /hello_chat
spring:
  datasource:
    name: hello
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///hello?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #监控统计
    filters: stat
    initial-size: 2 #初始化连接
    max-idle: 10 #最大空闲连接数
    min-idle: 1 # 最小空闲连接数
    max-active: 20 # 最大活动连接
    max-wait: 60000 # 获取连接超时的等待时间
    # 间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-evict-runs-millis: 60000
    #连接在池中的最小生存时间
    min-evictable-idle-time-millis: 300000
    # 验证连接有效与否的sql
    validation-query: SELECT 'X'
 # redis连接配置
  redis:
    host: 39.99.175.29
    port: 6378
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  jpa:
    show-sql: true
mybatis:
  mapper-locations: classpath:com/hrj/mapper/*Mapper.xml
# 打印sql




